server:
  port: 7001
  servlet:
    context-path: /cybersecurity

spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/cybersecurity?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC+8
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.cybersecurityawareness.model

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
